# Generated by Django 5.2.7 on 2025-11-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('receivers', models.JSONField()),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('urgent', 'Urgent'), ('announcement', 'Announcement')], max_length=20)),
                ('urgent', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.JSONField(default=dict)),
            ],
        ),
    ]
