# Generated by Django 5.2.7 on 2025-11-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subject_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectwiseMark',
            fields=[
                ('subjectwise_Mark_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Term', models.CharField(max_length=10)),
                ('Marks_Obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Max_Marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Date_Recorded', models.DateTimeField(auto_now_add=True)),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mark_id', to='admin_panel.studentdetail')),
                ('Subject_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='term_test.subject')),
                ('Teacher_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_marking', to='admin_panel.teacherdetail')),
            ],
        ),
        migrations.CreateModel(
            name='TermTest',
            fields=[
                ('term_summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('average_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank', models.IntegerField()),
                ('pass_fail_status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.studentdetail')),
            ],
        ),
    ]
