# Generated by Django 5.2.7 on 2025-11-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0002_alter_studentdetail_enrolledclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermTest',
            fields=[
                ('term_summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('average_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank', models.IntegerField()),
                ('pass_fail_status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.studentdetail')),
            ],
        ),
    ]
