# Generated by Django 5.2.7 on 2025-11-20 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectID', models.AutoField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termName', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectwiseMark',
            fields=[
                ('subjectWiseMarkID', models.BigAutoField(primary_key=True, serialize=False)),
                ('marksObtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dateRecorded', models.DateTimeField(auto_now_add=True)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectwisemark', to='admin_panel.studentdetail')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectwisemark', to='term_test.subject')),
                ('teacherID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectwisemark', to='admin_panel.teacherdetail')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectwisemark', to='term_test.termname')),
            ],
        ),
        migrations.CreateModel(
            name='TermTest',
            fields=[
                ('termtestId', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('average', models.DecimalField(decimal_places=2, max_digits=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termtest', to='admin_panel.studentdetail')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termtest', to='term_test.termname')),
            ],
        ),
    ]
