# Generated by Django 5.2.7 on 2025-11-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termtest',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=10),
        ),
    ]
