# Generated by Django 5.2.7 on 2025-11-16 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectwisemark',
            name='Term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_term', to='term_test.termtest'),
        ),
        migrations.AlterField(
            model_name='termtest',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='termtest',
            name='term_summary_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
