# Generated by Django 5.2.7 on 2025-11-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectwisemark',
            old_name='Date_Recorded',
            new_name='dateRecorded',
        ),
        migrations.RenameField(
            model_name='subjectwisemark',
            old_name='Teacher_ID',
            new_name='teacherID',
        ),
    ]
