# Generated by Django 5.2.7 on 2025-11-17 14:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=1)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuardianDetail',
            fields=[
                ('guardianId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('guardianNIC', models.CharField(max_length=20, unique=True)),
                ('guardianName', models.CharField(max_length=100000)),
                ('guardianType', models.CharField(blank=True, choices=[('M', 'Mother'), ('F', 'Father'), ('G', 'Guardian')], max_length=1)),
                ('guardianEmail', models.EmailField(max_length=254, unique=True)),
                ('permanentAddress', models.TextField()),
                ('currentAddress', models.TextField()),
                ('guardianContactNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits and may start with +', regex='^\\+?\\d{9,15}$')])),
                ('alternativeContactNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits and may start with +', regex='^\\+?\\d{9,15}$')])),
                ('jobTitle', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherNIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_number', models.CharField(max_length=25, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('indexNumber', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('surName', models.CharField(max_length=100)),
                ('fullName', models.CharField(max_length=300)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('enrollmentDate', models.DateField()),
                ('mobileNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits and may start with +', regex='^\\+?\\d{9,15}$')])),
                ('enrolledClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admin_panel.classroom')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='admin_panel.guardiandetail')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('teacherId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('surName', models.CharField(blank=True, max_length=100, null=True)),
                ('fullName', models.CharField(blank=True, max_length=300, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('enrollmentDate', models.DateField(blank=True, null=True)),
                ('mobileNumber', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits and may start with +', regex='^\\+?\\d{9,15}$')])),
                ('section', models.CharField(blank=True, max_length=300, null=True)),
                ('assignedClass', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='admin_panel.classroom')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
                ('nic_number', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.teachernic')),
            ],
        ),
    ]
