# Generated by Django 5.2.7 on 2025-11-05 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guardian_details',
            fields=[
                ('guardian_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('guardian_name', models.CharField(max_length=100000)),
                ('guardian_type', models.CharField(choices=[('M', 'Mother'), ('F', 'Father'), ('G', 'Guardian')], max_length=1)),
                ('guardian_email', models.EmailField(max_length=254, unique=True)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('guar_con_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits and may start with +', regex='^\\+?\\d{9,15}$')])),
                ('alternative_con_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits and may start with +', regex='^\\+?\\d{9,15}$')])),
                ('job_title', models.CharField(max_length=100000)),
            ],
        ),
    ]
