# Generated by Django 5.2.7 on 2025-11-23 08:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=1)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuardianDetail',
            fields=[
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Ven', 'Ven')], max_length=10, null=True)),
                ('guardianId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('guardianNIC', models.CharField(max_length=20, unique=True)),
                ('guardianName', models.CharField(max_length=100000)),
                ('guardianType', models.CharField(blank=True, choices=[('M', 'Mother'), ('F', 'Father'), ('G', 'Guardian')], max_length=1)),
                ('guardianEmail', models.EmailField(max_length=254, unique=True)),
                ('permanentAddress', models.TextField()),
                ('currentAddress', models.TextField()),
                ('guardianContactNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits and may start with +', regex='^\\+?\\d{9,15}$')])),
                ('alternativeContactNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits and may start with +', regex='^\\+?\\d{9,15}$')])),
                ('jobTitle', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='StaffNIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_number', models.CharField(max_length=25, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('indexNumber', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nameWithInitials', models.CharField(blank=True, max_length=100, null=True)),
                ('fullName', models.CharField(max_length=300)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('enrollmentDate', models.DateField()),
                ('mobileNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits and may start with +', regex='^\\+?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetail',
            fields=[
                ('teacherId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Ven', 'Ven')], max_length=20, null=True)),
                ('nameWithInitials', models.CharField(blank=True, max_length=100, null=True)),
                ('fullName', models.CharField(blank=True, max_length=300, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('enrollmentDate', models.DateField(blank=True, null=True)),
                ('mobileNumber', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits and may start with +', regex='^\\+?\\d{9,15}$')])),
                ('section', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('adminProfileID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Ven', 'Ven')], max_length=20, null=True)),
                ('nameWithInitials', models.CharField(blank=True, max_length=100, null=True)),
                ('fullName', models.CharField(blank=True, max_length=300, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('enrollmentDate', models.DateField(blank=True, null=True)),
                ('mobileNumber', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits and may start with +', regex='^\\+?\\d{9,15}$')])),
                ('position', models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('Section Head', 'Section Head'), ('Staff Admin', 'Staff Admin')], max_length=20, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubjectAssignment',
            fields=[
                ('assignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.classroom')),
            ],
        ),
    ]
