# Generated by Django 5.2.7 on 2025-11-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardiandetail',
            name='guardianNic',
        ),
        migrations.AddField(
            model_name='guardiandetail',
            name='guardianNIC',
            field=models.CharField(default=2911161, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
