# Generated by Django 5.2.7 on 2025-11-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='className',
            field=models.CharField(max_length=1),
        ),
    ]
