# Generated by Django 5.2.7 on 2025-11-21 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('term_test', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term_test.subject'),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='enrolledClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admin_panel.classroom'),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='admin_panel.guardiandetail'),
        ),
        migrations.AddField(
            model_name='teacherdetail',
            name='assignedClass',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='admin_panel.classroom'),
        ),
        migrations.AddField(
            model_name='teacherdetail',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherdetail',
            name='teachingClasses',
            field=models.ManyToManyField(blank=True, related_name='subteachers', to='admin_panel.classroom'),
        ),
        migrations.AddField(
            model_name='classsubjectassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='admin_panel.teacherdetail'),
        ),
        migrations.AddField(
            model_name='teacherdetail',
            name='nic_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.teachernic'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubjectassignment',
            unique_together={('classroom', 'subject')},
        ),
    ]
