# Generated by Django 5.2.7 on 2025-11-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_guardiandetail_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherdetail',
            old_name='firstName',
            new_name='nameWithInitials',
        ),
        migrations.RemoveField(
            model_name='teacherdetail',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='teacherdetail',
            name='surName',
        ),
        migrations.AlterField(
            model_name='teacherdetail',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
