# Generated by Django 5.2.7 on 2025-11-22 11:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherNIC',
            new_name='StaffNIC',
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('adminProfileID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Ven', 'Ven')], max_length=20, null=True)),
                ('nameWithInitials', models.CharField(blank=True, max_length=100, null=True)),
                ('fullName', models.CharField(blank=True, max_length=300, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('enrollmentDate', models.DateField(blank=True, null=True)),
                ('mobileNumber', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 9–15 digits and may start with +', regex='^\\+?\\d{9,15}$')])),
                ('Position', models.CharField(blank=True, choices=[('P', 'Principal'), ('VP', 'Vice Principal'), ('SH', 'Section Head'), ('SA', 'Staff Admin')], max_length=5, null=True)),
                ('nic_number', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.staffnic')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
