# Generated by Django 5.2.7 on 2025-11-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdetail',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Ven', 'Ven')], max_length=20, null=True),
        ),
    ]
