# Generated by Django 5.2.7 on 2025-11-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename_teachernic_staffnic_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='Position',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('Section Head', 'Section Head'), ('Staff Admin', 'Staff Admin')], max_length=20, null=True),
        ),
    ]
