# Generated by Django 5.2.7 on 2025-11-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherAttendence',
            fields=[
                ('attendence_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=7)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.teacherdetail')),
            ],
        ),
        migrations.CreateModel(
            name='studentAttendence',
            fields=[
                ('attendenceId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('isMarked', models.BooleanField(default=False)),
                ('presentPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('absentList', models.JSONField(blank=True, default=list, null=True)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendence', to='admin_panel.classroom')),
            ],
            options={
                'unique_together': {('className', 'date')},
            },
        ),
    ]
