# Generated by Django 5.2.7 on 2025-11-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentAttendence',
            fields=[
                ('attendenceId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.studentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='teacherAttendence',
            fields=[
                ('attendence_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=7)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.teacherdetail')),
            ],
        ),
    ]
