# Generated by Django 5.2.7 on 2025-11-23 08:57

import SystemSettings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(blank=True, max_length=100)),
                ('motto', models.TextField()),
                ('principalName', models.CharField(blank=True, max_length=100)),
                ('principlSignature', models.ImageField(upload_to='signatures/', validators=[SystemSettings.models.validatePNG])),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
