# Generated by Django 5.2.7 on 2025-12-31 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SystemSettings', '0001_initial'),
        ('term_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccycleconfig',
            name='current_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='term_test.termname'),
        ),
    ]
