# Generated by Django 5.2.7 on 2025-11-24 04:00

import SystemSettings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemSettings', '0001_initial'),
        ('term_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldetail',
            name='principlSignature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', validators=[SystemSettings.models.validatePNG]),
        ),
        migrations.CreateModel(
            name='AcademicCycleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='term_test.termname')),
            ],
        ),
    ]
